### ISSUE TITLE
Schematic QTH-090-01-L-D-A.lib fix ups

### ISSUE THREAD

**Issue by mithro** [brightcloudy/mithro-fps#1]
- [ ] Rename the .lib file to HSMC.lib
- [ ] Make a couple of HSMC parts based on the different HSMC configurations (and the QTH-090-01-L-D-A part). Pins should be labelled per the HSMC spec.
  - [ ] HSMC - Standard Single-Ended Configuration
  - [ ] HSMC - Standard Differential Configuration

**Comment by brightcloudy** [comment]
Changes made, and the standard single-ended/differential configuration schematic parts added.
